language: node_js

node_js:
  - '10'

branches:
  only:
  - master
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
  - /^\d+\.\d+?$/

notifications:
  email:
    on_success: never


install:
  - travis_retry npm ci

script:
  - npm run production
  - ./dist/franc-bin-linux "let's try the build with a simple string"

before_deploy: npm run production

deploy:
  provider: releases
  api_key: "${GITHUB_OAUTH}"
  file: 
    - "dist/franc-bin-linux"
    - "dist/franc-bin-macos"
    - "dist/franc-bin-win.exe"
  skip_cleanup: true
  on:
    tags: true