language: node_js
node_js:
  - '8'

notifications:
  email:
    on_success: never


install:
  - travis_retry npm install

script:
  - ls

before_deploy: npm run production

deploy:
  provider: releases
  api_key: "${GITHUB_OAUTH}"
  file: 
    - "dist/franc-bin-linux"
    - "dist/franc-bin-macos"
    - "dist/franc-bin-win.exe"
  skip_cleanup: true
  on:
    tags: true